#!/usr/bin/env bash
REPOSITORY=https://raw.github.com/coderjoe/laptop/ubuntify

bash < <(curl -s ${REPOSITORY}/lib/ubuntu/packages)
bash < <(curl -s ${REPOSITORY}/lib/ubuntu/github)
bash < <(curl -s ${REPOSITORY}/lib/ubuntu/rvm)
bash < <(curl -s ${REPOSITORY}/ruby)
