#!/usr/bin/env bash

OPENCMD=open
[[ -f /usr/bin/kde-open ]] && OPENCMD=kde-open
[[ -f /usr/bin/gnome-open ]] && OPENCMD=gnome-open

echo "Checking for SSH key, generating one if it exists ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | xclip
  ${OPENCMD} https://github.com/account/ssh
